//* Style
import './global.css';

export const metadata = {
	title: 'Locomotive Scroll',
	description: 'Generated by Karlen Nersisyan',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>{children}</body>
		</html>
	);
}
